USE [master]
GO

/****** Object:  Database [LearningManagementSystem]    Script Date: 6/4/2025 5:37:01 PM ******/
CREATE DATABASE [LearningManagementSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DS_1403_09_SK', FILENAME = N'E:\Data Science\SQLServerFile\Data\DS_1403_09_SK.mdf' , SIZE = 307200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 307200KB )
 LOG ON 
( NAME = N'DS_1403_09_SK_log', FILENAME = N'E:\Data Science\SQLServerFile\Log\DS_1403_09_SK_log.ldf' , SIZE = 122880KB , MAXSIZE = 2048GB , FILEGROWTH = 122880KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LearningManagementSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LearningManagementSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LearningManagementSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LearningManagementSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LearningManagementSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LearningManagementSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [LearningManagementSystem] SET  MULTI_USER 
GO

ALTER DATABASE [LearningManagementSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LearningManagementSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LearningManagementSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LearningManagementSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LearningManagementSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LearningManagementSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LearningManagementSystem] SET QUERY_STORE = ON
GO

ALTER DATABASE [LearningManagementSystem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [LearningManagementSystem] SET  READ_WRITE 
GO


